version: '3'

services:
    mindmap-restapi:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
        environment:
            - FLASK_ENV=production
