version: '3'

services:
    mindmap-restapi:
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        ports:
            - 3000:3000
        environment:
            - FLASK_ENV=development
            - FLASK_APP=index.py
        volumes:
          - .:/app
