FROM python:3.10-alpine

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt

ENV FLASK_ENV=development
ENV FLASK_APP=index.py
EXPOSE 3000
ENTRYPOINT [ "flask", "run", "-h", "0.0.0.0", "-p", "3000" ]
